# your domain
domain: proxypool-demo2.herokuapp.com
port: 12580                 # default 12580

# source list file
source-files:
#   # use local file
#   - ./source.yaml
  # use web file
  - https://raw.githubusercontent.com/kivid/myOpenwrt/main/config.d/proxypoolsource.yaml

# ======= 可选项，留空使用default值  =======
# 虽然有速度上千兆的但发现是被墙了的节点，这里就不测速了用国内机


# postgresql database info
database_url: "postgres://postgres:6666@159.138.153.86:5432/proxypool2" # 为了避免冲突不连

# interval between each crawling
crawl-interval:       # v0.5.x default 60 (minutes)
crontime:             # v0.4.x default 60 (minutes). Deprecated in the newest version

# speed test
speedtest: false      # default false. Warning: this will consume large network resources.
speedtest-interval:   # default 720 (min)
connection:           # default 5. The number of speed test connections simultaneously
timeout:              # default 10 (seconds).
## active proxy speed test
active-interval:      # default 60 (min)
active-frequency:     # default 100 (requests per interval)
active-max-number:    # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""
