name: autoepic
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use docker image
        uses: docker://luminoleon/epicgames
      - name: test
        run: docker images
      - name: run docker interact
        run: docker run -d luminoleon/epicgames-claimer -u ${{ secrets.EPIC.USERNAME }} -p ${{ secrets.EPIC.PASSWORD }}

