name: autoepic
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'
jobs:
  my_job:
    runs-on: ubuntu-20.04
    container:
      image: luminoleon/epicgames-claimer
      env:
        NODE_ENV: development
        TZ: Asia/Shanghai
        EMAIL: ${{ secrets.EPIC.USERNAME }}
        PASSWORD: ${{ secrets.EPIC.PASSWORD }}
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
#       options: --cpus 1
    steps:
      - name: check
        run: ls & ps-aux
      - name: run
        run: date ; sleep 1m ; date
# jobs: 
#   autorun:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: checkout
#         uses: actions/checkout@v2
#       - name: run docker container
#         uses: docker://luminoleon/epicgames-claimer
#         with:
#           args:
#       - name: run docker interact
#         run: docker run -d luminoleon/epicgames-claimer -u ${{ secrets.EPIC.USERNAME }} -p ${{ secrets.EPIC.PASSWORD }}

